#include "platform.h"
#include "pick_char.h"
#include "gameplay.h"
#include "menu_select1.h"
#include "menu_select2.h"
#include "menu_select3.h"
#include "bitbang_splash.h"
#include "redarrow.h"
#include "bluearrow.h"
#include "greenarrow0.h"
#include "greenarrow1.h"

// number images
#include "zero.h"
#include "one.h"
#include "two.h"
#include "three.h"
#include "four.h"
#include "five.h"
#include "six.h"
#include "seven.h"
#include "eight.h"
#include "nine.h"

// field images
#include "battlefield1.h"
#include "pokemon_stadium.h"

// character images.
#include "yoshi.h"
#include "kirby.h"
#include "link.h"
#include "pickachu.h"
#include "falco.h"
#include "donkeykong.h"
#include "mario.h"
#include "luigi.h"
#include "fox.h"
