#include "platform.h"
#include "pick_char.h"
#include "menu_select1.h"
#include "menu_select2.h"
#include "menu_select3.h"
#include "bitbang_splash.h"
#include "redarrow.h"
#include "bluearrow.h"
#include "greenarrow0.h"
#include "greenarrow1.h"
//#include "player1_win.h"
//#include "player0_win.h"
#include "pick_stage.h"

// number images
#include "zero.h"
#include "one.h"
#include "two.h"
#include "three.h"
#include "four.h"
#include "five.h"
#include "six.h"
#include "seven.h"
#include "eight.h"
#include "nine.h"

// field images
#include "pokemon_stadium.h"
#include "corneria.h"
#include "brinstar2.h"
#include "paradise.h"
#include "mario_level.h"
#include "saffron.h"
#include "yoshis_island.h"
#include "hyrule.h"
#include "final_destination.h"

// character images.
#include "yoshi.h"
#include "kirby.h"
#include "link.h"
#include "pickachu.h"
#include "falco.h"
#include "donkeykong.h"
#include "mario.h"
#include "luigi.h"
#include "fox.h"
